// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAuwVWTwHbBNzPQKtNg8HEHCqc_tOxNHQ',
    appId: '1:438782047284:web:1322a75bfdb28073fa4661',
    messagingSenderId: '438782047284',
    projectId: 'reelstek',
    authDomain: 'reelstek.firebaseapp.com',
    storageBucket: 'reelstek.firebasestorage.app',
    measurementId: 'G-NZDJB9GNQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhtDT9dMxe76K9navF6kGy2eJrS8J_f5Q',
    appId: '1:438782047284:android:fce0dc2ad8c2e1b3fa4661',
    messagingSenderId: '438782047284',
    projectId: 'reelstek',
    storageBucket: 'reelstek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD0A1WLcFzlxcFUEqmKnYPNvqFeq_A2GA',
    appId: '1:438782047284:ios:d1f778b9bb9f6434fa4661',
    messagingSenderId: '438782047284',
    projectId: 'reelstek',
    storageBucket: 'reelstek.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD0A1WLcFzlxcFUEqmKnYPNvqFeq_A2GA',
    appId: '1:438782047284:ios:d1f778b9bb9f6434fa4661',
    messagingSenderId: '438782047284',
    projectId: 'reelstek',
    storageBucket: 'reelstek.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAuwVWTwHbBNzPQKtNg8HEHCqc_tOxNHQ',
    appId: '1:438782047284:web:2333fea9e40bf15dfa4661',
    messagingSenderId: '438782047284',
    projectId: 'reelstek',
    authDomain: 'reelstek.firebaseapp.com',
    storageBucket: 'reelstek.firebasestorage.app',
    measurementId: 'G-LBB36TLF04',
  );
}
